// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/echo.proto

/*
Package Chat is a generated protocol buffer package.

It is generated from these files:
	protos/echo.proto

It has these top-level messages:
	RegisterRequest
	RegisterResponse
	BroadcastRequest
	BroadcastResponse
*/
package Chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type RegisterResponse struct {
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BroadcastRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *BroadcastRequest) Reset()                    { *m = BroadcastRequest{} }
func (m *BroadcastRequest) String() string            { return proto.CompactTextString(m) }
func (*BroadcastRequest) ProtoMessage()               {}
func (*BroadcastRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BroadcastRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BroadcastResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *BroadcastResponse) Reset()                    { *m = BroadcastResponse{} }
func (m *BroadcastResponse) String() string            { return proto.CompactTextString(m) }
func (*BroadcastResponse) ProtoMessage()               {}
func (*BroadcastResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BroadcastResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "Chat.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "Chat.RegisterResponse")
	proto.RegisterType((*BroadcastRequest)(nil), "Chat.BroadcastRequest")
	proto.RegisterType((*BroadcastResponse)(nil), "Chat.BroadcastResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chat service

type ChatClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Broadcast(ctx context.Context, opts ...grpc.CallOption) (Chat_BroadcastClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/Chat.Chat/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Broadcast(ctx context.Context, opts ...grpc.CallOption) (Chat_BroadcastClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Chat_serviceDesc.Streams[0], c.cc, "/Chat.Chat/Broadcast", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatBroadcastClient{stream}
	return x, nil
}

type Chat_BroadcastClient interface {
	Send(*BroadcastRequest) error
	Recv() (*BroadcastResponse, error)
	grpc.ClientStream
}

type chatBroadcastClient struct {
	grpc.ClientStream
}

func (x *chatBroadcastClient) Send(m *BroadcastRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatBroadcastClient) Recv() (*BroadcastResponse, error) {
	m := new(BroadcastResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Chat service

type ChatServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Broadcast(Chat_BroadcastServer) error
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Chat.Chat/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Broadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Broadcast(&chatBroadcastServer{stream})
}

type Chat_BroadcastServer interface {
	Send(*BroadcastResponse) error
	Recv() (*BroadcastRequest, error)
	grpc.ServerStream
}

type chatBroadcastServer struct {
	grpc.ServerStream
}

func (x *chatBroadcastServer) Send(m *BroadcastResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatBroadcastServer) Recv() (*BroadcastRequest, error) {
	m := new(BroadcastRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Chat_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Broadcast",
			Handler:       _Chat_Broadcast_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/echo.proto",
}

func init() { proto.RegisterFile("protos/echo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4d, 0xce, 0xc8, 0xd7, 0x03, 0xb3, 0x85, 0x58, 0x9c, 0x33, 0x12, 0x4b,
	0x94, 0x74, 0xb9, 0xf8, 0x83, 0x52, 0xd3, 0x33, 0x8b, 0x4b, 0x52, 0x8b, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x92, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0x3c, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x25, 0x21, 0x2e, 0x01, 0x84, 0xf2, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x25, 0x1d, 0x2e, 0x01, 0xa7, 0xa2, 0xfc, 0xc4, 0x94, 0xe4, 0xc4, 0xe2,
	0x12, 0x98, 0x19, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x50, 0x23, 0x60,
	0x5c, 0x25, 0x5d, 0x2e, 0x41, 0x24, 0xd5, 0x10, 0x23, 0x70, 0x2b, 0x37, 0x6a, 0x67, 0xe4, 0x02,
	0x3b, 0x54, 0xc8, 0x9a, 0x8b, 0x03, 0x66, 0xb3, 0x90, 0xa8, 0x1e, 0x48, 0x48, 0x0f, 0xcd, 0xe1,
	0x52, 0x62, 0xe8, 0xc2, 0x50, 0x07, 0x32, 0x08, 0x39, 0x71, 0x71, 0xc2, 0x2d, 0x15, 0x82, 0x2a,
	0x43, 0x77, 0xb3, 0x94, 0x38, 0x86, 0x38, 0x4c, 0xbf, 0x06, 0xa3, 0x01, 0x63, 0x12, 0x1b, 0x38,
	0xd8, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xb0, 0x71, 0x26, 0x4b, 0x01, 0x00, 0x00,
}
